title: Service

columns:
  - width: 1/1
    sections:
      header:
        type: fields
        fields:
          pageTitleHeader:
            label: Header
            type: headline
          titlePage:
            label: Title
            type: text
  - width: 1/1
    fields:
      pageTitleServices:
        label: Services
        type: headline
      titleServices:
        label: Title
        type: text
      subtitleServices:
        label: Subtitle
        type: text
      services:
        type: structure
        label: List
        fields:
          titleText:
            label: Title Text
            type: text
          text:
            label: Text
            type: text
          delay:
            label: Delay Animation
            type: text
          images:
            label: Img
            type: files
          icon:
            label: Icon
            type: text
          link:
            label: Link
            type: url

  - width: 1/1
    sections:
      about:
        type: fields
        fields:
          pageTitleWhy:
            label: Why
            type: headline
          whySubtitle:
            label: Subtitle
            type: text
          whyTitle:
            label: Title
            type: text
          whyText:
            label: Text
            type: text
          whyItems:
            type: structure
            label: List
            fields:
              whyItemSubtitle:
                label: Subtitle
                type: text
              whyItemTitle:
                label: Title
                type: text
              whyItemIcon:
                label: Icon
                type: text
          whyFiles:
            label: Img
            type: files
