title: Service

columns:
  - width: 1/1
    sections:
      header:
        type: fields
        fields:
          pageTitleHeader:
            label: Header
            type: headline
          titlePage:
            label: Title
            type: text
  - width: 1/1
    fields:
      pageTitleServices:
        label: Services
        type: headline
      titleServices:
        label: Title
        type: text
      subtitleServices:
        label: Subtitle
        type: text
      services:
        type: structure
        label: List
        fields:
          titleText:
            label: Title Text
            type: text
          text:
            label: Text
            type: text
          delay:
            label: Delay Animation
            type: text
          images:
            label: Img
            type: files
          icon:
            label: Icon
            type: text
          link:
            label: Link
            type: url

  - width: 1/1
    sections:
      about:
        type: fields
        fields:
          pageTitleAbout:
            label: About
            type: headline
          aboutSubtitle:
            label: Subtitle
            type: text
          aboutTitle:
            label: Title
            type: text
          aboutText:
            label: Text
            type: text
          aboutList:
            label: List
            type: list
            marks:
              - bold
              - italic
              - strike
          aboutFiles:
            label: Img
            type: files
            disabled: true
  - width: 1/1
    sections:
      team:
        type: fields
        fields:
          pageTitleTeam:
            label: Team
            type: headline
          teamSubtitle:
            label: Subtitle
            type: text
            width: 1/3
          teamTitle:
            label: Title
            type: text
            width: 2/3
          members:
            type: structure
            label: Members
            fields:
              titleCard:
                label: Title
                type: text
              text:
                label: Text
                type: text
              count:
                label: Count
                type: number
              icon:
                label: Icon
                type: text
              delay:
                label: Delay Animation
                type: text
